[versions]

kotlin = "2.0.0"
ktor = "2.3.11"
logback = "1.5.6"

[libraries]

# Ktor
ktor_core_jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor_server_config_yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor_server_netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

# Logging
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Tests
kotlin_junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
ktor_server_tests_jvm = { module = "io.ktor:ktor-server-tests-jvm", version.ref = "ktor" }

[plugins]

kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

[bundles]

ktor_all = [
    "ktor_core_jvm",
    "ktor_server_config_yaml",
    "ktor_server_netty"
]

tests_all = [
    "kotlin_junit",
    "ktor_server_tests_jvm"
]
